добавил взаимодействие с базой данных
JugglypuffM/Kotlin-App-Server pull request #3
Opened 2024-10-12 19:40 UTC by AHDEPCEH

Прикрутил Postgres
Добавил класс для взаимодействия с бд, и класс - таблицу, идея такова:
Один класс будет обращаться ко всем таблицам и извлекать данные, передавать всё классам на подсосе, которые будут реализовывать интерфейс. 
Также добавил библиотеку Dotenv, так что нужно создать файл .env c:
PORT= - порт на котором развёрнут сервер бд
NAMEDB=имя бд(по умолчанию postgres)
USER= пользователь бд(по стандарту postgres)
PASSWORD=

2024-10-12 20:27 UTC, JugglypuffM requested changes

2024-10-12 20:27 UTC, JugglypuffM commented on src/main/kotlin/database/DatabasePerson.kt
> +    //TODO Сделать кеш запросов, чтобы сократить количество запросов в бд
Хорошая идея, делай, главное чтобы он сильно много оперативы не занимал - постарайся оптимизировать

2024-10-12 20:27 UTC, JugglypuffM commented on src/main/kotlin/database/DatabasePerson.kt
> +}
Теперь пришло время обратить на слона в комнате, я ещё в прошлый раз хотел поднять этот вопрос, но стало как-то лень, да и захотелось создать челлендж по решению проблем при уже написанном коде.
В общем: а что мы с тобой будем делать, когда мне придется фильтровать пользователей по всякому: возвращать всех, возвращать только мужиков, только друзей конкретного пользователя, только тех кто прошел 10км, только тех кто прошел Афган и тд?

2024-10-12 20:27 UTC, JugglypuffM commented on src/main/kotlin/domain/Person.kt
>  ){
Вот тут очень некрасиво получилось, мне кажется: типа у меня уже очень много кода, в котором этот класс используется, а тут ты его бац и поменял - теперь мне придется тоже. Так лучше не делать, но тут иначе и нельзя, вот почему: это очень глубокая проблема, за которую, мне кажется, нам придется поплатиться: при регистрации заполняются не все данные, следовательно создавать объект который хранит как раз все данные - не лучшее решение, лучше разбить объект на аккаунт и данные аккаунта, в нашем случае мне во-первых, _персона_-льно не нравится слово _Person_ для названия - пусть уж лучше привычный **User**, а во-вторых, вместо того чтобы в юзера добавлять все данные, лучше добавить в качестве его поля контейнер со всеми его данными и тогда получится что сам по себе юзер будет содержать только креды и контейнер с данными, которые уже можно заполнить позже, да и архитектурно мне кажется будет выглядеть красивее

2024-10-12 20:27 UTC, JugglypuffM commented on pom.xml
> +        </dependency>
👉👈
Добавь комментик с описанием пжшка)

2024-10-12 20:27 UTC, JugglypuffM commented on src/main/kotlin/database/DatabasePerson.kt
> +}
Это кстати как раз вопрос к той архитектуре, которую ты _описал в описании_ пр-а

2024-10-12 20:32 UTC, AHDEPCEH commented on src/main/kotlin/database/DBManager.kt
> +                SchemaUtils.create(Users)
Прога не упадёт из-за блока try
Бд не упадёт, так как там просто вылетит исключение из postgres, что такая таблица есть, так что это нормальная практика: так как экземпляр один, при запуске сервера, чтобы можно было не создавать таблицу с пользователями самостоятельно.

2024-10-12 20:34 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabasePerson.kt
> +        //TODO обработка ошибок - записи нет в бд
Да, я забыл подтереть todo, потому что решил возвращать у всех операций исход (boolean)

2024-10-12 20:36 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabasePerson.kt
> +        //TODO Обработка ошибок - такого пользователя не существует
У нас с Артёмом было очень хорошее решение для этого случая: создание собственных ошибок. Я думаю, что на первое время сойдёт это, но в будущем я думал пробрасывать ошибки

2024-10-12 20:36 UTC, JugglypuffM commented on src/main/kotlin/database/DBManager.kt
> +                SchemaUtils.create(Users)
То есть дропа данных тоже быть не может?

2024-10-12 20:39 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabasePerson.kt
> +}
Хороший вопрос, архитектура это позволит, только нужно расширять колонки таблицы и возможно менеджера бд. Вот только тогда получится, что этот класс будет перегружен функционалом. Я подумаю над решением

2024-10-12 20:39 UTC, AHDEPCEH commented on src/main/kotlin/database/DBManager.kt
> +                SchemaUtils.create(Users)
Да, они останутся в сохранности, инфа 100%

2024-10-12 20:39 UTC, JugglypuffM commented on src/main/kotlin/database/DatabasePerson.kt
> +        //TODO Обработка ошибок - такого пользователя не существует
Крутое решение, в целом наверное лучше его сейчас применить, потому что "зачем откладывать на потом то, сделать сейчас"☝️_ауф_

2024-10-17 18:20 UTC, syoumzic commented on src/main/kotlin/database/DatabasePerson.kt
> +}
Мне кажется, что тут будет резонно реализовывать методы под конкретные задачи (getUsersWithGenger, getUsersWithDistance и т.д.). Конечно можно реализовать и более мобильные методы (выбрать пользователе, отсортировать по конкретному полю) но это слишком сложно создать и слишком сложно поддерживать

2024-10-17 18:20 UTC, syoumzic commented on src/main/kotlin/domain/Person.kt
>  ){
Можно использовать класс Person (User) так, чтобы можно было опираться на расширение его полей. В коде Person пока используется в AuthentificatorImpl 
```
val person = Person(name, login, password)
```
Предлагаю динамически его создавать 
```
val person = Person.setName()
                   .setAge()
                   .setPassword()
```
чтобы потом можно было добавить .setDistance().setGender() к примеру

2024-10-23 16:48 UTC, JugglypuffM submitted a review, later dismissed
Вроде норм, только добавь все таки комментик в pom.xml, чтобы я конверс резолвнул)

2024-10-23 16:48 UTC, JugglypuffM commented on pom.xml
> +        </dependency>
Пропустил

2024-10-23 17:12 UTC, AHDEPCEH commented on pom.xml
> +        </dependency>
ничего не понял, куда какой коммент оставить, в поме всё есть же

2024-10-23 17:24 UTC, JugglypuffM commented on pom.xml
> +        </dependency>
В поме у каждой зависимости есть коммент - что это такое,а тут нету
Это не особо важно, но пусть лучше будет - так красивее

2024-10-24 11:30 UTC, JugglypuffM reviewed
Пара вопросов

2024-10-24 11:30 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseUsers.kt
> +}
Может имеет смысл выделить все такие объекты(ведь наверняка будут еще другие таблицы) в отдельный пакет и хранить их там, отдельно от реализации бд

2024-10-24 11:30 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseUsers.kt
> +    val id : Column<String> = varchar("id", 10)
чего это вдруг стринг, откуда мы его брать будем, почему бы не генерировать автоматически

2024-10-25 07:05 UTC, AHDEPCEH commented on pom.xml
> +        </dependency>
Так он там есть

2024-10-25 10:49 UTC, JugglypuffM commented on pom.xml
> +        </dependency>
Блин, да зайди, посмотри на строчки, к которым я отсылаюсь, я ведь не шизойд, надеюсь)
Нету комментария у этого депенденси![Screenshot_20241025-154759.png](https://github.com/user-attachments/assets/30367ad5-0b30-4845-84ec-ca7ebd2004c9)

2024-10-25 12:28 UTC, AHDEPCEH commented on src/main/kotlin/Exception/DatabaseException.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
Можно, но я думал это так себе практика пихать всё в файл с интерфейсом

2024-10-25 12:31 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabaseUsers.kt
> +    val id : Column<String> = varchar("id", 10)
Короче, я считаю, что нужно сделать так: допустим будем генерить id пользователя в бд при регистрации, и допустим возвращать его методом add, чтобы затем отправить на устройство, так как я без понятия как ты собрался различать пользователей, чтобы получать в дальнейшем их данные из бд. Если ты планировал делать это по логину, то какой тогда в этом смысл, если ты мне сам говорил, что это плохая идея или я тебя не понял.

2024-10-25 12:34 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabaseUsers.kt
> +}
Пускай таблица для пользователей будет одна, оставь ты её в покое, мне не составит труда поддерживать такой код и при надобности добавить туда несколько полей. А в коде мы при необходимости добавим новые датаклассы, по типу: UserExtension и добавить пару методов для бд, чтобы получать доп информацию пучком, когда мы уже определимся что конкретно будем хранить из доп информации.

2024-10-25 12:36 UTC, JugglypuffM commented on src/main/kotlin/Exception/DatabaseException.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
все - плохая, но исключения напрямую с ним связаны

2024-10-25 12:41 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseUsers.kt
> +    val id : Column<String> = varchar("id", 10)
если хочешь сделать логин главным ключем - то напиши что это логин, если хочешь оставить id то сделай его числом и генерь автоматически, это может пригодиться чтобы в других таблицах размер вторичного ключа был меньше(типа хранить в таблице с тренировками id дешевле чем строку, при чем сильно)

2024-10-25 12:47 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseUsers.kt
> +}
но я вообще не про это...
я про то что хранить два объекта в одном файле - нестандартная практика

2024-10-25 15:09 UTC, JugglypuffM requested changes
Переименовать переменные окружения, чтобы не было пересечений и добавить зависимость kotlin-reflect

2024-10-27 06:11 UTC, syoumzic reviewed
всё ок, только поправь замечания

2024-11-05 10:46 UTC, JugglypuffM approved these changes
Все норм, вроде, одна мелочь только есть

2024-11-05 10:46 UTC, JugglypuffM commented on src/main/kotlin/domain/Account.kt
> +    }
Пусть будет просто Account()

2024-11-05 10:51 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseTable.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
Не приметил, это лучше внести внутрь какого-нибудь объекта, который эти исключения выбрасывает, просто для иерархии - типа исключения бд это часть объекта бд, который их производит

2024-11-05 11:18 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabaseTable.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
В менеджер бд?

2024-11-05 11:19 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabaseTable.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
Ну а вообще его вроде как выбрасывают в таблицах, и ему и а интерфесе неплохо живётся

2024-11-05 11:20 UTC, AHDEPCEH commented on src/main/kotlin/domain/Account.kt
> +    }
Ага, не заметил

2024-11-07 06:54 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseTable.kt
> +class DatabaseException(message: String, cause: Throwable? = null) : Exception(message, cause)
Я как раз про то, что сейчас класс исключения не включен в интерфейс, и его бы туда, наверное, надо бы занести

2024-11-07 08:55 UTC, JugglypuffM requested changes

2024-11-07 08:55 UTC, JugglypuffM commented on src/main/kotlin/database/DatabaseManager.kt
> +    }
Надо бы переименовать, потому что это не пользователь, да эта информация даже не должна содержать идентификатор

2024-11-07 08:55 UTC, JugglypuffM commented on src/main/kotlin/database/DbTableUsers.kt
Тут тоже название не соответствует сути

2024-11-07 08:55 UTC, JugglypuffM commented on src/main/kotlin/database/DbTableUsers.kt
> +    }
Если этот объект описывает информацию о пользователе, то этот метод не так должен работать

2024-11-11 15:41 UTC, AHDEPCEH commented on src/main/kotlin/database/DatabaseManager.kt
> +    }
Не понял о каком идентификаторе ты говоришь, но согласен переименовать

2024-11-15 12:49 UTC, JugglypuffM approved these changes
Очень рад, что принял к сведению пожелание про коммиты, есть одно замечание: в одном коммите ты и код поправил по стилю(style), и пофиксил что-то(fix), и отрефачил немного(refactor)
В идеале разбивать в таких случаях на несколько коммитов
По коду вроде нет вопросов, да и надоело уже этот пр ревьюить)))

2024-11-15 12:50 UTC, JugglypuffM commented
А, ну поправь быстренько toString у аккаунта, чтобы я конверс ресолвнул

2024-11-19 09:58 UTC, merged