Добавлена обработка запросов личной информации пользователя и еще рефактор бд
JugglypuffM/Kotlin-App-Server pull request #9
Opened 2024-11-19 13:52 UTC by JugglypuffM

2024-11-22 08:10 UTC, AHDEPCEH requested changes
Короче всё ничего, но не нужно лезть в мою архитектуру больше. Я выделил тебе синглтон, чтобы ты его использовал, если тебе что-то нужно от бд.

2024-11-22 08:10 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DbTableMock.kt
> +class DbTableMock : DAO<Account> {
Тут почему-то осталось старое название

2024-11-22 08:10 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Зачем было создавать интерфейс? У него будет всего одна реализация - это бесполезно. Если нужно будет добавлять методы в менеджер, а их надо будет добавлять, то интерфейс чисто для того чтобы в него их потом тоже добавлять? Звучит как бесполезный интерфейс, я считаю, что нужно вернуть как было.

2024-11-22 08:44 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Хехе, нихуя)
Это самое важное изменение: как минимум для тестов - как ты мне предлагаешь тестировать классы которые используют объект с реальным коннектом к бд? Интерфейс нужен, чтобы можно было легко и непринужденно мокать бд. А как максимум еще было бы неплохо иметь in-memory реализацию этого интерфейса чтобы ручное тестирование не требовало поднятия настоящей бд

2024-11-22 08:46 UTC, JugglypuffM commented
Согласен, не очень красиво получилось - мне так было проще, чем писать тебе в комментах к пру
В следующий раз учту

2024-11-22 08:54 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DbTableMock.kt
> +class DbTableMock : DAO<Account> {
Ну это я понимаю, просто странно выходит, ладно пусть так будет

2024-11-22 08:57 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Что ты там собрался тестировать? Если эти методы тупо выполняют обращение к бд. У тебя был мок, вот его и используй, но даже в нём отпала нужда. Я без понятия как ты это планируешь тестировать и не вижу в этом смысла

2024-11-22 08:58 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Погоди, ты предлагаешь не тестировать логику сервера?

2024-11-22 08:59 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Да даже если и так, то тесты уже написаны

2024-11-22 08:59 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Не вижу смысла сохранять данные в памяти программы. Типо для чего? Если бд упадёт, так это и так конец будет. А если на всякий случай, то как бы зачем, если нам нужно проверять работу бд

2024-11-22 09:01 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Зачем хранить тесты, которые ничего не тестируют?

2024-11-22 09:01 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Я же объяснил: для ручного тестирования
Не для реального использования

2024-11-22 09:02 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Тестировать нормально стоит только сложную логику сервера, а запись в бд нормально не протестировать никогда, только если вручную

2024-11-22 09:02 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Я и не собираюсь бд тестировать - сомнительное мероприятие

2024-11-22 09:06 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Но при этом ты хочешь тестировать логику на валидацию данных пользователей, которые зависят от правильности работы бд, что там тестировать:/

2024-11-22 09:07 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Или я без понятия, что ты хочешь тестировать в логике сервера

2024-11-22 09:08 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
> Но при этом ты хочешь тестировать логику на валидацию данных пользователей, которые зависят от правильности работы бд, что там тестировать:/

Совсем не понял о чем ты

2024-11-22 09:09 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
> Или я без понятия, что ты хочешь тестировать в логике сервера

корректность работы сервисов

2024-11-22 09:12 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Тесты для аутентификатора, сервиса аутентификации и сервиса получения данных пользователя существуют с момента реализации оных, и они используют бд; но если я избавлюсь от интерфейса и буду использовать твой синглтон напрямую - эти для проавильной работы этих тестов придется каждый раз поднимать пустую бд, что противоречит концепции юнит тестирования

2024-11-22 09:17 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Я не понимаю, почему нельзя просто мокнуть этого менеджера и тестировать с Моком, а не поддерживать другую схожую реализацию, которая всё сохраняет в памяти

2024-11-22 09:18 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManager.kt
Это выглядит как будто тесты поползли в архитектуру

2024-11-22 09:21 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManager.kt
Нееее, реализация в памяти вообще не для тестов - тут ты прав: я буду искать менеджера, и для нормального пока нужен интерфейс

2024-11-27 10:32 UTC, AHDEPCEH approved these changes

2024-11-27 10:33 UTC, AHDEPCEH commented
Можешь мёрджить, решил, что буду поддерживать бд в памяти

2024-11-27 10:34 UTC, merged